/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import modelos.demografia;
import modelos.persona;
import modelos.relacionesForaneas;

/**
 *
 * @author isacc
 */
public class detallesP extends javax.swing.JFrame {

    /**
     * Creates new form demografia
     */
    int xMause, yMause, x, y;

    static DefaultTableModel modelo;

    public detallesP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panel_barra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dc = new javax.swing.JLayeredPane();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new Clases.ScrollPaneWin11();
        jTable1 = new javax.swing.JTable();
        dp = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panel_dc = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_barra.setBackground(new Color(255,255,255,50));
        panel_barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_barraMouseDragged(evt);
            }
        });
        panel_barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_barraMousePressed(evt);
            }
        });
        panel_barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Salir");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panel_barra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 40, 30));

        jPanel1.add(panel_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        dc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Nombre de la comunidad");
        dc.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 290, -1));

        jLabel17.setText("Cantidad de Habitantes");
        dc.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jLabel18.setText("Cantidad de Calles");
        dc.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 110, -1));

        jLabel19.setText("Cantidad de Lideres de Calle");
        dc.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, -1, -1));

        jLabel20.setText("Cantidad de Hombre");
        dc.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 140, -1));

        jLabel21.setText("Cantidad de Mujeres");
        dc.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 140, -1));

        jLabel22.setText("Cantidad de niños");
        dc.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 110, -1));

        jLabel23.setText("00");
        dc.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, -1, -1));

        jLabel24.setText("00");
        dc.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        jLabel25.setText("00");
        dc.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 120, -1, -1));

        jLabel26.setText("00");
        dc.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 160, -1, -1));

        jLabel27.setText("00");
        dc.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, -1, -1));

        jLabel28.setText("00");
        dc.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Lideres de cada calle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setDefaultRenderer(Object.class, new Clases.table.TableGradientCell(new Color(153,204,255),new Color(255,153,255)));
        jScrollPane3.setViewportView(jTable1);

        dc.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 440, 310));

        jPanel1.add(dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 43, 460, 537));

        dp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Perfil Detallado del Habitante");
        dp.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 350, 23));
        dp.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 282, 390, -1));

        jLabel9.setText("Edad:");
        dp.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 290, -1));

        jLabel10.setText("Calle principal, casa sin numero");
        dp.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 390, 30));
        dp.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 390, -1));

        jLabel8.setText("18 años, actualmente");
        dp.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 390, 30));

        jScrollPane1.setBackground(new Color(255,255,255,30));
        jScrollPane1.setBorder(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        dp.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 400, 60));
        dp.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 522, 390, -1));

        jLabel4.setText("El 28 de Octubre del 2005");
        dp.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 390, 30));

        jLabel15.setText("Condicion de Salud:");
        dp.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 290, -1));

        jLabel12.setText("Nivel de instruccion mas alto, Educación Media \"Bachiller\"");
        dp.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 390, 30));

        jLabel5.setText("Fecha de Nacimiente:");
        dp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, -1));

        jLabel16.setText("Integrantes de la familia:");
        dp.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 290, -1));

        jScrollPane2.setBackground(new Color(255,255,255,30));
        jScrollPane2.setBorder(null);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(null);
        jScrollPane2.setViewportView(jTextArea2);

        dp.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 400, 60));

        jLabel7.setText("Ezequiel  Isacc  Ardiles  Campos");
        dp.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 390, 30));
        dp.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 342, 390, 10));

        jLabel11.setText("Dirección:");
        dp.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 300, -1));
        dp.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 432, 390, -1));
        dp.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 222, 390, -1));

        jLabel6.setText("Nombre Completo:");
        dp.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 280, -1));

        jLabel13.setText("Datos Academicos:");
        dp.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 290, -1));
        dp.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 390, -1));

        jPanel1.add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 43, 460, 537));

        panel_dc.setBackground(new Color(255,255,255,150));
        panel_dc.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0,0,204,50)));
        panel_dc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panel_dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 43, 460, 537));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoInfoPersona.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_barraMouseDragged
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();

        setLocation(x - xMause, y - yMause);
    }//GEN-LAST:event_panel_barraMouseDragged

    private void panel_barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_barraMousePressed
        xMause = evt.getX();
        yMause = evt.getY();
    }//GEN-LAST:event_panel_barraMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detallesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detallesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detallesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detallesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detallesP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLayeredPane dc;
    private static javax.swing.JLayeredPane dp;
    private javax.swing.JLabel jLabel1;
    private static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private static javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private static javax.swing.JLabel jLabel23;
    private static javax.swing.JLabel jLabel24;
    private static javax.swing.JLabel jLabel25;
    private static javax.swing.JLabel jLabel26;
    private static javax.swing.JLabel jLabel27;
    private static javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private static javax.swing.JLabel jLabel7;
    private static javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel panel_barra;
    private javax.swing.JPanel panel_dc;
    // End of variables declaration//GEN-END:variables

    public static void cDetalles() {
        jLabel24.setText(String.valueOf(demografia.cantidadStrike()));
        jLabel28.setText(String.valueOf(demografia.cantidadLiderSk()));
        jLabel25.setText(String.valueOf(persona.cantidadPersona()));
        jLabel27.setText(String.valueOf(persona.cantidadPersonaH()));
        jLabel26.setText(String.valueOf(persona.cantidadPersonaM()));
        jLabel23.setText(String.valueOf(persona.cantidadPersonaNN()));

        modelo = new DefaultTableModel(){
            boolean[] canEdit = new boolean[]{
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        String[] colums = {"Lideres de Calle"};
        modelo.setColumnIdentifiers(colums);

        for (String[] aux : demografia.rescuAll()) {
            modelo.addRow(new String[]{""});
            modelo.addRow(new String[]{aux[0]});
            modelo.addRow(new String[]{aux[1]+" "+aux[2]+" "+aux[3]+" "+aux[4]+" CI:"+aux[5]});

        }
        jTable1.setModel(modelo);
        dinamicDetalles("comunidad");
    }

    public static void pDetalles() throws ParseException {
        
        persona.buscar(persona.getId());
        SimpleDateFormat formato = new SimpleDateFormat("dd 'de' MMMM 'del' yyyy");

        jLabel7.setText(persona.getpNombre() + " " + persona.getsNombre() + ", " + persona.getpApellido() + " " + persona.getsApellido());

        jLabel4.setText("El " + formato.format(persona.getFechaN()));
       
        Date fecha;
        fecha = formato.parse((String) formato.format(persona.getFechaN()));
        Period periodo = Period.between(fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), LocalDate.now());
        int years = periodo.getYears();
        jLabel8.setText(years + " actualmente");
        
        int id_direccion = 0;
        String numeroC = "N/A";
        ArrayList<String[]> lista = modelos.house.buscarHause();
        for (String[] aux : lista) {
            id_direccion = Integer.parseInt(aux[3]);
                numeroC = String.valueOf(aux[1]);
            
        }
        
        relacionesForaneas.setId_demografia(id_direccion);
        jLabel10.setText(relacionesForaneas.nDemografia() + " #Casa: " + numeroC);

        relacionesForaneas.setId_mgAcademico(persona.getMgAcademico());
        jLabel12.setText("Nivel de instrucción mas alto alcanzado, " + relacionesForaneas.nMgAcademico());
        dinamicDetalles("persona");
    }

    public static void dinamicDetalles(String menu) {
        switch (menu) {
            case "persona":
                dp.setVisible(true);
                dc.setVisible(false);
                break;
            case "comunidad":
                dp.setVisible(false);
                dc.setVisible(true);
                break;
        }
    }
}
