/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.Period;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import modelos.demografia;
import modelos.discapacidades;
import modelos.house;
import modelos.persona;
import modelos.relacionesForaneas;

/**
 *
 * @author isacc
 */
public class detallesP extends javax.swing.JFrame {

    /**
     * Creates new form demografia
     */
    int xMause, yMause, x, y;
    private static int ttHabitantes;
    private static int hombres;
    private static int mujeres;
    private static int ninos;

    static DefaultTableModel modelo;

    public detallesP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_base = new javax.swing.JPanel();
        panel_barra = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dc = new javax.swing.JLayeredPane();
        text_totalH = new javax.swing.JLabel();
        eticketa_infoDemografai = new javax.swing.JLabel();
        eticketa_ttHabintantes = new javax.swing.JLabel();
        eticketa_strike = new javax.swing.JLabel();
        eticketa_lider = new javax.swing.JLabel();
        eticketa_ttH = new javax.swing.JLabel();
        eticketa_ttM = new javax.swing.JLabel();
        eticketa_ttNn = new javax.swing.JLabel();
        text_ttNn = new javax.swing.JLabel();
        text_strike = new javax.swing.JLabel();
        text_ttHabitante = new javax.swing.JLabel();
        text_ttM = new javax.swing.JLabel();
        text_Lider = new javax.swing.JLabel();
        jScrollPane3 = new Clases.ScrollPaneWin11();
        tabla_estructua = new javax.swing.JTable();
        barraNN = new Clases.ProgressBarCustom();
        barraTTh = new Clases.ProgressBarCustom();
        barraH = new Clases.ProgressBarCustom();
        barraM = new Clases.ProgressBarCustom();
        dp = new javax.swing.JLayeredPane();
        jLabel3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        eticketa_edad = new javax.swing.JLabel();
        lebel_direcc = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lebel_edad = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_salud = new javax.swing.JTextArea();
        jSeparator7 = new javax.swing.JSeparator();
        label_fechaN = new javax.swing.JLabel();
        etick_salud = new javax.swing.JLabel();
        lebel_educc = new javax.swing.JLabel();
        eticketa_fechaN = new javax.swing.JLabel();
        eticketa_famila = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        text_familia = new javax.swing.JTextArea();
        label_nombre = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        eticketa_direcc = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        eticketa_nombre = new javax.swing.JLabel();
        eticketa_educacion = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        panelD = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panel_base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_barra.setBackground(new Color(255,255,255,50));
        panel_barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panel_barraMouseDragged(evt);
            }
        });
        panel_barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panel_barraMousePressed(evt);
            }
        });
        panel_barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setText("Salir");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panel_barra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 0, 40, 30));

        panel_base.add(panel_barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 30));

        dc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        text_totalH.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text_totalH.setText("00");
        dc.add(text_totalH, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, -1, 20));

        eticketa_infoDemografai.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        eticketa_infoDemografai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eticketa_infoDemografai.setText("Informacion demografica");
        dc.add(eticketa_infoDemografai, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 290, -1));

        eticketa_ttHabintantes.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        eticketa_ttHabintantes.setText("Cantidad de Habitantes");
        dc.add(eticketa_ttHabintantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 20));

        eticketa_strike.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        eticketa_strike.setText("Cantidad de Calles");
        dc.add(eticketa_strike, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        eticketa_lider.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        eticketa_lider.setText("Cantidad de Lideres de Calle");
        dc.add(eticketa_lider, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        eticketa_ttH.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        eticketa_ttH.setText("Cantidad de Hombre");
        dc.add(eticketa_ttH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, 20));

        eticketa_ttM.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        eticketa_ttM.setText("Cantidad de Mujeres");
        dc.add(eticketa_ttM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, 20));

        eticketa_ttNn.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        eticketa_ttNn.setText("Cantidad de niños");
        dc.add(eticketa_ttNn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        text_ttNn.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text_ttNn.setText("00");
        dc.add(text_ttNn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, -1, 20));

        text_strike.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text_strike.setText("00");
        dc.add(text_strike, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        text_ttHabitante.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text_ttHabitante.setText("000000");
        dc.add(text_ttHabitante, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, -1, 20));

        text_ttM.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text_ttM.setText("00");
        dc.add(text_ttM, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, 20));

        text_Lider.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        text_Lider.setText("00");
        dc.add(text_Lider, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        tabla_estructua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Lideres de cada calle"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla_estructua.setDefaultRenderer(Object.class, new Clases.table.TableGradientCell(new Color(153,204,255),new Color(255,153,255)));
        jScrollPane3.setViewportView(tabla_estructua);

        dc.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 440, 310));

        barraNN.setBorder(null);
        barraNN.setForeground(new java.awt.Color(255, 131, 38));
        barraNN.setValue(80);
        barraNN.setColorString(new java.awt.Color(255, 255, 255));
        dc.add(barraNN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 390, 20));

        barraTTh.setBorder(null);
        barraTTh.setForeground(new java.awt.Color(104, 169, 49));
        barraTTh.setValue(80);
        barraTTh.setColorString(new java.awt.Color(255, 255, 255));
        dc.add(barraTTh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 390, 20));

        barraH.setBorder(null);
        barraH.setValue(80);
        barraH.setColorString(new java.awt.Color(255, 255, 255));
        dc.add(barraH, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 390, 20));

        barraM.setBorder(null);
        barraM.setForeground(new java.awt.Color(255, 0, 255));
        barraM.setValue(80);
        barraM.setColorString(new java.awt.Color(255, 255, 255));
        dc.add(barraM, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 390, 20));

        panel_base.add(dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 43, 460, 537));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Datos del Habitante");

        eticketa_edad.setText("Edad:");

        lebel_direcc.setText("Calle principal, casa sin numero");

        lebel_edad.setText("18 años, actualmente");

        jScrollPane1.setBackground(new Color(255,255,255,30));
        jScrollPane1.setBorder(null);

        text_salud.setColumns(20);
        text_salud.setRows(5);
        text_salud.setBorder(null);
        jScrollPane1.setViewportView(text_salud);

        label_fechaN.setText("El 28 de Octubre del 2005");

        etick_salud.setText("Condicion de Salud:");

        lebel_educc.setText("Nivel de instruccion mas alto, Educación Media \"Bachiller\"");

        eticketa_fechaN.setText("Fecha de Nacimiente:");

        eticketa_famila.setText("Integrantes de la familia:");

        jScrollPane2.setBackground(new Color(255,255,255,30));
        jScrollPane2.setBorder(null);

        text_familia.setColumns(20);
        text_familia.setRows(5);
        text_familia.setBorder(null);
        jScrollPane2.setViewportView(text_familia);

        label_nombre.setText("Ezequiel  Isacc  Ardiles  Campos");

        eticketa_direcc.setText("Dirección:");

        eticketa_nombre.setText("Nombre Completo:");

        eticketa_educacion.setText("Datos Academicos:");

        dp.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jSeparator4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(eticketa_edad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(lebel_direcc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jSeparator2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(lebel_edad, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jSeparator7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(label_fechaN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(etick_salud, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(lebel_educc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(eticketa_fechaN, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(eticketa_famila, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jScrollPane2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(label_nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jSeparator5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(eticketa_direcc, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jSeparator6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jSeparator3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(eticketa_nombre, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(eticketa_educacion, javax.swing.JLayeredPane.DEFAULT_LAYER);
        dp.setLayer(jSeparator1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout dpLayout = new javax.swing.GroupLayout(dp);
        dp.setLayout(dpLayout);
        dpLayout.setHorizontalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(eticketa_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(eticketa_fechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(label_fechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(eticketa_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lebel_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(eticketa_direcc, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lebel_direcc, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(eticketa_educacion, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lebel_educc, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etick_salud, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(eticketa_famila, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        dpLayout.setVerticalGroup(
            dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(eticketa_nombre)
                .addGap(6, 6, 6)
                .addComponent(label_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(eticketa_fechaN)
                .addGap(6, 6, 6)
                .addComponent(label_fechaN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(eticketa_edad)
                .addGap(6, 6, 6)
                .addComponent(lebel_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(eticketa_direcc)
                .addGap(6, 6, 6)
                .addComponent(lebel_direcc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(eticketa_educacion)
                .addGap(6, 6, 6)
                .addComponent(lebel_educc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(dpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dpLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(etick_salud))
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(eticketa_famila)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panel_base.add(dp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 43, 460, 537));

        panelD.setBackground(new Color(255,255,255,150));
        panelD.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(0,0,204,50)));

        javax.swing.GroupLayout panelDLayout = new javax.swing.GroupLayout(panelD);
        panelD.setLayout(panelDLayout);
        panelDLayout.setHorizontalGroup(
            panelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelDLayout.setVerticalGroup(
            panelDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panel_base.add(panelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 43, 460, 537));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoInfoPersona.png"))); // NOI18N
        panel_base.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(panel_base, "card2");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void panel_barraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_barraMouseDragged
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();

        setLocation(x - xMause, y - yMause);
    }//GEN-LAST:event_panel_barraMouseDragged

    private void panel_barraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panel_barraMousePressed
        xMause = evt.getX();
        yMause = evt.getY();
    }//GEN-LAST:event_panel_barraMousePressed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(detallesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(detallesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(detallesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(detallesP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new detallesP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static Clases.ProgressBarCustom barraH;
    private static Clases.ProgressBarCustom barraM;
    private static Clases.ProgressBarCustom barraNN;
    private static Clases.ProgressBarCustom barraTTh;
    private static javax.swing.JLayeredPane dc;
    private static javax.swing.JLayeredPane dp;
    private static javax.swing.JLabel etick_salud;
    private javax.swing.JLabel eticketa_direcc;
    private javax.swing.JLabel eticketa_edad;
    private javax.swing.JLabel eticketa_educacion;
    private javax.swing.JLabel eticketa_famila;
    private javax.swing.JLabel eticketa_fechaN;
    private javax.swing.JLabel eticketa_infoDemografai;
    private javax.swing.JLabel eticketa_lider;
    private javax.swing.JLabel eticketa_nombre;
    private javax.swing.JLabel eticketa_strike;
    private javax.swing.JLabel eticketa_ttH;
    private javax.swing.JLabel eticketa_ttHabintantes;
    private javax.swing.JLabel eticketa_ttM;
    private javax.swing.JLabel eticketa_ttNn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private static javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private static javax.swing.JLabel label_fechaN;
    private static javax.swing.JLabel label_nombre;
    private static javax.swing.JLabel lebel_direcc;
    private static javax.swing.JLabel lebel_edad;
    private static javax.swing.JLabel lebel_educc;
    private javax.swing.JPanel panelD;
    private javax.swing.JPanel panel_barra;
    private javax.swing.JPanel panel_base;
    private static javax.swing.JTable tabla_estructua;
    private static javax.swing.JLabel text_Lider;
    private static javax.swing.JTextArea text_familia;
    private static javax.swing.JTextArea text_salud;
    private static javax.swing.JLabel text_strike;
    private static javax.swing.JLabel text_totalH;
    private static javax.swing.JLabel text_ttHabitante;
    private static javax.swing.JLabel text_ttM;
    private static javax.swing.JLabel text_ttNn;
    // End of variables declaration//GEN-END:variables

    public static void cDetalles() {
        ttHabitantes = persona.cantidadPersona();
        hombres = persona.cantidadPersonaH();
        mujeres = persona.cantidadPersonaM();
        ninos = persona.cantidadPersonaNN();
        
        barraTTh.setValue(100);
        
        barraH.setValue((hombres*ttHabitantes)/100);
        barraM.setValue((mujeres*ttHabitantes)/100);
        barraNN.setValue((ninos*ttHabitantes)/100);
        
        text_strike.setText(String.valueOf(demografia.cantidadStrike()));
        text_Lider.setText(String.valueOf(demografia.cantidadLiderSk()));
        text_ttHabitante.setText(String.valueOf(persona.cantidadPersona()));
        text_totalH.setText(String.valueOf(persona.cantidadPersonaH()));
        text_ttM.setText(String.valueOf(persona.cantidadPersonaM()));
        text_ttNn.setText(String.valueOf(persona.cantidadPersonaNN()));

        modelo = new DefaultTableModel() {
            boolean[] canEdit = new boolean[]{
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        };
        String[] colums = {"Lideres de Calle"};
        modelo.setColumnIdentifiers(colums);

        for (String[] aux : demografia.rescuAll()) {
            modelo.addRow(new String[]{""});
            modelo.addRow(new String[]{aux[0]});
            modelo.addRow(new String[]{aux[1] + " " + aux[2] + " " + aux[3] + " " + aux[4] + " CI:" + aux[5]});

        }
        tabla_estructua.setModel(modelo);
        dinamicDetalles("comunidad");
    }

    public static void pDetalles() throws ParseException {

        persona.buscar(persona.getId());
        SimpleDateFormat formato = new SimpleDateFormat("dd 'de' MMMM 'del' yyyy");

        label_nombre.setText(persona.getpNombre() + " " + persona.getsNombre() + ", " + persona.getpApellido() + " " + persona.getsApellido());

        label_fechaN.setText("El " + formato.format(persona.getFechaN()));

        Date fecha;
        fecha = formato.parse((String) formato.format(persona.getFechaN()));
        Period periodo = Period.between(fecha.toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), LocalDate.now());
        int years = periodo.getYears();
        lebel_edad.setText(years + " actualmente");

        int id_direccion = 0;
        String numeroC = "N/A";
        ArrayList<String[]> lista = modelos.house.buscarHause();
        for (String[] aux : lista) {
            id_direccion = Integer.parseInt(aux[3]);
            numeroC = String.valueOf(aux[1]);

        }

        relacionesForaneas.setId_demografia(id_direccion);
        lebel_direcc.setText(relacionesForaneas.nDemografia() + " #Casa: " + numeroC);

        relacionesForaneas.setId_mgAcademico(persona.getMgAcademico());
        lebel_educc.setText("Nivel de instrucción mas alto alcanzado, " + relacionesForaneas.nMgAcademico());
        dinamicDetalles("persona");

        ArrayList<String> listaD = discapacidades.disDP(persona.getId());
        if (listaD.size() > 0) {
            etick_salud.setVisible(true);
            jScrollPane1.setVisible(true);
            StringBuilder lddTxt = new StringBuilder();
            lddTxt.append("Tiene: \n");
            for (String aux : listaD) {
                lddTxt.append(aux + " \n");
            }
            text_salud.setText(lddTxt.toString());
        } else {
            etick_salud.setVisible(false);
            jScrollPane1.setVisible(false);
        }
        ArrayList<String[]> listaFp = persona.buscarPersonaXhause(house.getIdCasa(), "");

        if (listaFp.size() > 0) {
            StringBuilder lfp = new StringBuilder();
            for (String[] aux : listaFp) {
                lfp.append(aux[1] + " " + aux[3] + ": " + aux[12] + "\n");
            }
            text_familia.setText(lfp.toString());
        }

    }

    public static void dinamicDetalles(String menu) {
        switch (menu) {
            case "persona":
                dp.setVisible(true);
                dc.setVisible(false);
                break;
            case "comunidad":
                dp.setVisible(false);
                dc.setVisible(true);
                break;
        }
    }
}
