/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import java.awt.Color;
import java.awt.Desktop;
import java.io.File;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.TextStyle;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.house;
import modelos.persona;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;

/**
 *
 * @author isacc-PC
 */
public class ImprimirCarta extends javax.swing.JFrame {

    /**
     * Creates new form ImprimirCarta
     */
    public ImprimirCarta() {
        initComponents();
        cargarTabla("");
        Clases.tabla.TableCustom.apply(jScrollPane1, Clases.tabla.TableCustom.TableType.MULTI_LINE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        panel_base = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_persona = new javax.swing.JTable();
        entrada_buscar = new javax.swing.JTextField();
        bt_imprimir = new elaprendiz.gui.button.ButtonAction();
        d_en_buscar = new javax.swing.JSeparator();
        etk_buscar = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panel_base.setBackground(new java.awt.Color(250, 250, 250));
        panel_base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla_persona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ));
        tabla_persona.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tabla_persona.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tabla_personaMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_persona);

        panel_base.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 148, 580, 341));

        entrada_buscar.setText("Buscar...");
        entrada_buscar.setBorder(null);
        entrada_buscar.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                entrada_buscarCaretUpdate(evt);
            }
        });
        entrada_buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                entrada_buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                entrada_buscarMouseExited(evt);
            }
        });
        panel_base.add(entrada_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, 300, 35));

        bt_imprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/imprimir 16x16.png"))); // NOI18N
        bt_imprimir.setText("Imprimir");
        bt_imprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_imprimirActionPerformed(evt);
            }
        });
        panel_base.add(bt_imprimir, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 80, -1, -1));

        d_en_buscar.setForeground(new java.awt.Color(153, 153, 153));
        d_en_buscar.setOpaque(true);
        panel_base.add(d_en_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, 300, -1));

        etk_buscar.setText("Buscar");
        etk_buscar.setVisible(false);
        panel_base.add(etk_buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 64, 70, 20));

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrar-sesion.png"))); // NOI18N
        jLabel1.setText("Salir");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(527, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_base.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 40));

        getContentPane().add(panel_base, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void entrada_buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrada_buscarMouseEntered
        d_en_buscar.setForeground(new Color(0, 0, 250));
        etk_buscar.setVisible(true);
        if (entrada_buscar.getText().equals("Buscar...") == true) {
            entrada_buscar.setText("");
        }
    }//GEN-LAST:event_entrada_buscarMouseEntered

    private void entrada_buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrada_buscarMouseExited
        if (entrada_buscar.getText().trim().equals("") == true) {
            entrada_buscar.setText("Buscar...");
            d_en_buscar.setForeground(new Color(153, 153, 153));
            etk_buscar.setVisible(false);
        }
    }//GEN-LAST:event_entrada_buscarMouseExited

    private void entrada_buscarCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_entrada_buscarCaretUpdate
        if (entrada_buscar.getText().equals("Buscar...") == true) {
            cargarTabla("");
        } else {
            cargarTabla(entrada_buscar.getText());
        }

    }//GEN-LAST:event_entrada_buscarCaretUpdate

    private void tabla_personaMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_personaMousePressed
        id = Integer.parseInt((String) tabla_persona.getValueAt(tabla_persona.getSelectedRow(), 0));
    }//GEN-LAST:event_tabla_personaMousePressed

    private void bt_imprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_imprimirActionPerformed
        persona.buscar(id);
        ArrayList<String[]> casa = house.buscarHause();
        for (String[] aux : casa) {
            modelos.relacionesForaneas.setId_demografia(Integer.parseInt(aux[3]));
            if(!aux[1].equals("null")){
            nCasa = aux[1];}else{
                nCasa = "";                                
            }
        }
        if (id != 0) {
            int i = JOptionPane.showConfirmDialog(null, "Quieres Imprimir una carta de residencia para: \n" + persona.getpNombre() + " " + persona.getsNombre() + " " + persona.getpApellido() + " " + persona.getsApellido());
            if (i == JOptionPane.OK_OPTION) {
                File file = showFileChooser();
                System.out.println(file.toString());
                Carta(file.toString());
                this.setVisible(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecciona a una persona primero");
        }
    }//GEN-LAST:event_bt_imprimirActionPerformed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();

        setLocation(x - xMause, y - yMause);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xMause = evt.getX();
        yMause = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        this.setVisible(false);
    }//GEN-LAST:event_jLabel1MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirCarta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ImprimirCarta().setVisible(true);
            }
        });
    }

    private void cargarTabla(String buscar) {
        ArrayList<String[]> lista = persona.RecuperarAll(buscar);
        modelo = new DefaultTableModel();
        colums = new String[]{"COD", "Nombre y Apellido", "Cedula"};

        modelo.setColumnIdentifiers(colums);
        for (String[] aux : lista) {
            modelo.addRow(new String[]{
                aux[0],
                aux[1] + " " + aux[2] + " " + aux[3] + " " + aux[4],
                aux[5]
            });
        }
        tabla_persona.setModel(modelo);
    }

    private void Carta(String ruta) {
        try {
            tiempoViviendo = Integer.parseInt(JOptionPane.showInputDialog("Cuantos años tiene viviendo " + persona.getpNombre() + " " + persona.getpApellido() + " en la comunidad"));
            StringBuilder contenido = new StringBuilder();
            StringBuilder fecha = new StringBuilder();
            LocalDate dia = LocalDate.now();

            contenido.append("Quienes Suscriben, voceros (as), del Consejo Comunal "
                    + "“La Unión” por medio de la presente hacemos constar que el ciudadano (a) ");
            contenido.append(persona.getpNombre() + " " + persona.getsNombre() + " " + persona.getpApellido() + " " + persona.getsApellido() + "");
            contenido.append(", titular de la cedula de identidad N° " + persona.getCedula());
            System.out.println(modelos.relacionesForaneas.nDemografia());
            contenido.append(" : Esta residenciado (a) en este Sector, en la Calle: " + modelos.relacionesForaneas.nDemografia());
            if (!nCasa.equals("")) {
                contenido.append(" Casa. N° " + nCasa);
            }
            contenido.append(", desde hace aproximadamente (" + tiempoViviendo + ") años.");
            fecha.append("Constancia que se exepide a la solicitud de la parte interesada en esta ciudad de "
                    + "Altagracia de Orituco, Sector “La Union” a los " + dia.getDayOfMonth() + " dias del mes de "
                    + dia.getMonth().getDisplayName(TextStyle.FULL, Locale.forLanguageTag("es")) + " del Año " + dia.getYear());

            JasperReport archivo = JasperCompileManager.compileReport(System.getProperty("user.dir") +"/carta/carta.jrxml");
            Map dato = new HashMap<String, Object>();
            dato.put("dato", contenido);
            dato.put("fecha", fecha);
            JasperPrint prin = JasperFillManager.fillReport(archivo, dato, new JREmptyDataSource());
            JasperExportManager.exportReportToPdfFile(prin, ruta + ".pdf");
            Desktop.getDesktop().open(new File(ruta + ".pdf"));
        } catch (JRException ex) {
            System.out.println(ex);
              JOptionPane.showMessageDialog(this, ex);
        } catch (IOException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "La entrada debe de ser numirica");
        }
    }

    //Codigo reutilizado autor, River
    private File showFileChooser() {
        JFileChooser ch = new JFileChooser();
        int opt = ch.showSaveDialog(this);
        if (opt == JFileChooser.APPROVE_OPTION) {
            return ch.getSelectedFile();
        } else {
            return null;
        }
    }
    int x, y, xMause, yMause;
    DefaultTableModel modelo;
    String[] colums;
    Integer id = 0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private elaprendiz.gui.button.ButtonAction bt_imprimir;
    private javax.swing.JSeparator d_en_buscar;
    private javax.swing.JTextField entrada_buscar;
    private javax.swing.JLabel etk_buscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panel_base;
    private javax.swing.JTable tabla_persona;
    // End of variables declaration//GEN-END:variables
private static int tiempoViviendo = 0;
    private static String nCasa = "";
}
