/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import modelos.*;
import java.awt.*;
import java.time.Clock;
import java.util.ArrayList;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Ezequiel Isacc
 */
public class modificar extends javax.swing.JFrame {

    /**
     * Creates new form modificar
     */
    int x,y,xMause,yMause;
    
    private Color nulo = new Color(153,153,153);
    private Color seleccionado = new Color(51,153,255);
    private Color disponible = new Color(0,0,0);
    
    int idPcambiarF;
    Integer seleccion = null;
    static DefaultTableModel modelo;
    static String[] listaRf;
    
    public static String[] cargarRfCbbx(){
        ArrayList<String[]> lista = relacionesForaneas.rsRolFamiar();
        listaRf = new String[lista.size()];
        int i = 0;
        for(String[] aux : lista){
            listaRf[i] = aux[1];
            i++;
        }
        return listaRf;
    }
    public modificar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_modificar = new javax.swing.JPanel(){
            @Override
            public void paintComponent(Graphics g) {
                super.paintComponent(g);

                GradientPaint gradient = new GradientPaint(0,getWidth(), new Color(137,59,234), getWidth(), 0, new Color(12,197,88));
                Graphics2D g2d = (Graphics2D) g;
                g2d.setPaint(gradient);
                g2d.fillRect(0,0,getWidth(), getHeight() );
            }
        };
        panelBarra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        md_familia = new javax.swing.JLayeredPane();
        jTextField15 = new javax.swing.JTextField();
        jLabel121 = new javax.swing.JLabel();
        jComboBox13 = new javax.swing.JComboBox<>();
        jScrollPane1 = new Clases.ScrollPaneWin11();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel122 = new javax.swing.JLabel();
        jLabel125 = new javax.swing.JLabel();
        jLabel124 = new javax.swing.JLabel();
        jLabel124.setForeground(new Color(0,0,0));
        jPanel1 = new javax.swing.JPanel();
        md_decoracion = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.CardLayout());

        panel_modificar.setPreferredSize(new java.awt.Dimension(800, 500));
        panel_modificar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelBarra.setBackground(new java.awt.Color(0,0,0,50));
        panelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraMouseDragged(evt);
            }
        });
        panelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraMousePressed(evt);
            }
        });
        panelBarra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/minimizar 25x15.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        panelBarra.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 6, 30, 20));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/Salir X 25x25.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        panelBarra.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 30, 30));

        panel_modificar.add(panelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        md_familia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField15.setText("Buscar..");
        jTextField15.setBorder(null);
        jTextField15.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                jTextField15CaretUpdate(evt);
            }
        });
        md_familia.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 260, 30));

        jLabel121.setText("Buscar familia");
        md_familia.add(jLabel121, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 80, -1));

        jComboBox13.setModel(new DefaultComboBoxModel<String>(cargarRfCbbx()));
        jComboBox13.setBorder(null);
        jComboBox13.setVisible(false);
        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });
        md_familia.add(jComboBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, 210, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.setDefaultRenderer(Object.class, new Clases.table.TableGradientCell(new Color(153,204,255),new Color(255,153,255)));
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        md_familia.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 760, 370));

        jLabel3.setForeground(new Color(0,0,0));
        jLabel3.setForeground(nulo        );
        jLabel3.setText("Cambiar de Famila");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        md_familia.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 54, 110, 20));

        jLabel122.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel122.setForeground(nulo);
        jLabel122.setText("Guardar");
        jLabel122.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel122MouseClicked(evt);
            }
        });
        md_familia.add(jLabel122, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 54, 60, 20));

        jLabel125.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        jLabel125.setForeground(nulo);
        jLabel125.setText("Descartar");
        jLabel125.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel125MouseClicked(evt);
            }
        });
        md_familia.add(jLabel125, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 76, 60, 20));

        jLabel124.setForeground(nulo);
        jLabel124.setText("Modificar Familia");
        jLabel124.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel124MouseClicked(evt);
            }
        });
        md_familia.add(jLabel124, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 76, 110, 20));

        jPanel1.setBackground(new Color(255,255,255,117));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(204,255,255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        md_familia.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 210, 50));

        panel_modificar.add(md_familia, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        md_decoracion.setBackground(new Color(255,255,255,150));
        md_decoracion.setPreferredSize(new java.awt.Dimension(760, 410));

        javax.swing.GroupLayout md_decoracionLayout = new javax.swing.GroupLayout(md_decoracion);
        md_decoracion.setLayout(md_decoracionLayout);
        md_decoracionLayout.setHorizontalGroup(
            md_decoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );
        md_decoracionLayout.setVerticalGroup(
            md_decoracionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        panel_modificar.add(md_decoracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 780, 450));

        getContentPane().add(panel_modificar, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField15CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_jTextField15CaretUpdate
        if(jLabel125.getForeground().equals(new Color(153,153,153))){
           cargarFamilia(jTextField15.getText());
        }
    }//GEN-LAST:event_jTextField15CaretUpdate

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
            if(seleccion != null){
               jTable1.setValueAt((String)jComboBox13.getSelectedItem(), seleccion, 0);
            }else{
               JOptionPane.showMessageDialog(null, "Seleccione una persona");
             }            
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jLabel124MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel124MouseClicked
        if(jLabel124.getForeground().equals(disponible) == true && jLabel3.getForeground().equals(disponible) == true){
            persona.buscar(persona.getId());
            ArrayList<String[]> lista = persona.buscarPersonaXhause(house.getIdCasa(), "");
            modelo = new DefaultTableModel();
            String[] colums = {"Rol familiar","Nombre y Apellido","Cedula","COD"};
            modelo.setColumnIdentifiers(colums);

            for(String [] aux : lista){           
                modelo.addRow(new String[]{aux[12],aux[1]+" "+aux[2]+" "+aux[3]+" "+aux[4],aux[5],aux[0]});
            }
            jComboBox13.setVisible(true);
            jTable1.setModel(modelo);
            jLabel124.setForeground(seleccionado);
            jLabel125.setForeground(disponible);
            jLabel122.setForeground(disponible);
            jLabel3.setForeground(nulo);
            seleccion = null;
        }
        
    }//GEN-LAST:event_jLabel124MouseClicked

    private void jLabel125MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel125MouseClicked
        if(jLabel125.getForeground().equals(disponible)){
            cargarFamilia("");
            jLabel125.setForeground(nulo);
            jLabel122.setForeground(nulo);
            jLabel124.setForeground(nulo);
            jLabel3.setForeground(nulo);
            seleccion = null;
            jComboBox13.setVisible(false);            
        }
    }//GEN-LAST:event_jLabel125MouseClicked

    private void panelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseDragged
        x = evt.getXOnScreen();
        y = evt.getYOnScreen();

        setLocation(x - xMause, y - yMause);
    }//GEN-LAST:event_panelBarraMouseDragged

    private void panelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMousePressed
        xMause = evt.getX();
        yMause = evt.getY();
    }//GEN-LAST:event_panelBarraMousePressed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
       this.setVisible(false);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        seleccion = jTable1.getSelectedRow();
        persona.setId(Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 3)));
        //relacionesForaneas.setId_rolFamiliar(Integer.parseInt((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0)));
        System.out.println(relacionesForaneas.nRolFamiliar());
        if(jLabel3.getForeground().equals(nulo) == true && jLabel124.getForeground().equals(seleccionado) == true){
            int i = 0;
            for(String aux : listaRf){                   
                if(aux.equals((String)jTable1.getValueAt(jTable1.getSelectedRow(), 0))){
                    jComboBox13.setSelectedIndex(i);
                    break;
                }
                i++;
            }
        }
        if(jLabel3.getForeground().equals(nulo) && jLabel124.getForeground().equals(nulo)){
            jLabel3.setForeground(disponible);
            jLabel124.setForeground(disponible);
        }        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel122MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel122MouseClicked
        if(jLabel122.getForeground().equals(disponible)){
            
            if(jLabel3.getForeground().equals(seleccionado)){
                /*@Cambiar a una persona de familia*/
                int id = persona.getId();
                persona.buscar(idPcambiarF);
                relacionesForaneas.setId_rolFamiliar(persona.getRolFamiliar());
                if(relacionesForaneas.nRolFamiliar().equals("Jefe de Familia") == false){
                    System.out.println("fayando x_.");
                    persona.cambiardFamilia(idPcambiarF , id);
                    JOptionPane.showMessageDialog(null, "se cambio de familia");
                    jLabel3.setForeground(nulo);
                    jLabel124.setForeground(nulo);
                    jLabel122.setForeground(nulo);
                    jLabel125.setForeground(nulo);
                    cargarFamilia("");
                    seleccion = null;
                    jComboBox13.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "¡¡No se puede puede cambiar un 'Jefe de Familia a otra Familia'!! primero tienes que cambiarle el rol de Jefe de Familia");
                }               
            }else{
                if(jLabel124.getForeground().equals(seleccionado)){
                    /*@Modificar los roles familiares de una familia*/                    
                    int estdJF = 0;
                    int estdCC = 0;
                    ArrayList<Integer[]> lista = new ArrayList<>();
                    for(int i = 0; i < jTable1.getRowCount();i++){
                        relacionesForaneas.setRolFamiliar((String)jTable1.getValueAt(i, 0));
                        if(jTable1.getValueAt(i, 0).equals("Jefe de Familia")){
                            estdJF++;
                        }
                        if(jTable1.getValueAt(i, 0).equals("Esposo(a)")){
                            estdCC++;
                        }
                        lista.add(new Integer[]{relacionesForaneas.buscarRolFamiliar(),Integer.parseInt((String)jTable1.getValueAt(i, 3))});
                    }
                    if(estdJF >= 1){
                        if(estdJF == 1){
                            if(estdCC < 2){
                                persona.modificarFamilia(lista);
                                Color cl = new Color(153,153,153);
                                jLabel125.setForeground(cl);
                                jLabel122.setForeground(cl);
                                cargarFamilia("");
                                jLabel3.setForeground(nulo);
                                jLabel124.setForeground(nulo);
                                jLabel122.setForeground(nulo);
                                jLabel125.setForeground(nulo);
                                seleccion = null;
                                jComboBox13.setVisible(false);
                                JOptionPane.showMessageDialog(null, "Se modifico la familia sin problema");
                            }else{                               
                                JOptionPane.showMessageDialog(null,"¡¡ERROR!! 'Solo no puede haber mas de un Cuncuno(a)'");
                            }                            
                        }else{
                            JOptionPane.showMessageDialog(null, "¡¡ERROR!! 'Solo puede haber un Jefe de Familia'");
                        }
                        
                    }else{
                        JOptionPane.showMessageDialog(null, "¡¡ERROR!! 'Debe de habre un Jefe de Famila'");
                    }                    
                }
            }                        
        }                
    }//GEN-LAST:event_jLabel122MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        System.out.println(jLabel3.getForeground());
        if(jLabel124.getForeground().equals(disponible) == true && jLabel3.getForeground().equals(disponible) == true){                  
            
            jLabel3.setForeground(seleccionado);
            jLabel122.setForeground(disponible);
            jLabel125.setForeground(disponible);
            jLabel124.setForeground(nulo);
            cargarFamilia("");
            idPcambiarF = persona.getId(); 
            JOptionPane.showMessageDialog(null, "Seleccione la persona a la que se le va añadir la carga familiar"); 
        }        
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(modificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new modificar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel121;
    private javax.swing.JLabel jLabel122;
    private javax.swing.JLabel jLabel124;
    private javax.swing.JLabel jLabel125;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JPanel md_decoracion;
    private javax.swing.JLayeredPane md_familia;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panel_modificar;
    // End of variables declaration//GEN-END:variables
    public static void cargarFamilia(String busqueda){
        ArrayList<String[]> lista = persona.RecuperarAll(busqueda);        
        modelo = new DefaultTableModel(){            
            boolean[] canEdit = new boolean [] {
            false, false, false, false
                };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];           
            };
        };
        String[] colums = {"Rol familiar","Nombres y Apellidos","Cedula","COD"};
        modelo.setColumnIdentifiers(colums);
        Integer i = 0;
        for(String [] aux : lista){
            if(i == Integer.parseInt(aux[13])){
                modelo.addRow(new String[]{aux[12],aux[1]+" "+aux[2]+" "+aux[3]+" "+aux[4],aux[5],aux[0]});
            }else{
                modelo.addRow(new String[]{"","","",""});
                modelo.addRow(new String[]{aux[12],aux[1]+" "+aux[2]+" "+aux[3]+" "+aux[4],aux[5],aux[0]});
                i = Integer.parseInt(aux[13]);
            }            
        }
        jTable1.setModel(modelo);
    }
}
